name: Trigger Jenkins Job (Clarisa Dev)

on:
  push:
    branches:
      - "dev" # Solo push a rama dev
  pull_request:
    branches:
      - "dev" # Solo PRs hacia dev
  workflow_dispatch: # También manual

jobs:
  trigger-job:
    runs-on: ubuntu-latest

    steps:
      - name: Build Jenkins Job URL
        run: |
          JENKINS_URL="https://automation.prms.cgiar.org/job/clarisa-application-dev/build"
          echo "JENKINS_URL=${JENKINS_URL}" >> $GITHUB_ENV

      - name: Trigger Jenkins Job
        run: |
          curl -X POST ${{ env.JENKINS_URL }} \
            --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_API_TOKEN }}
        env:
          JENKINS_URL: ${{ env.JENKINS_URL }}
          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
